# Generated by Django 5.2.17 on 2026-08-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='vat_rate',
            field=models.PositiveSmallIntegerField(choices=[(23, '23% (standard)'), (8, '8% (reduced)')], default=23, help_text="Snapshot of the product's VAT rate at the time of purchase."),
        ),
    ]
