# Generated by Django 5.2.17 on 2026-08-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(choices=[('inpost', 'InPost Parcel Locker'), ('dhl', 'DHL'), ('dpd', 'DPD'), ('ups', 'UPS')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('is_flat_rate', models.BooleanField(default=True)),
                ('flat_rate_pln', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cost_per_kg_pln', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('free_shipping_threshold_pln', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_days_min', models.PositiveSmallIntegerField(default=1)),
                ('estimated_days_max', models.PositiveSmallIntegerField(default=3)),
                ('requires_locker_selection', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['flat_rate_pln'],
            },
        ),
    ]
