# Generated by Django 5.2.17 on 2026-08-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specs',
            field=models.JSONField(blank=True, default=dict, help_text="Sport-specific spec table, e.g. {'weight_g': 300, 'head_size_sq_in': 100}"),
        ),
    ]
