# Generated by Django 5.2.17 on 2026-08-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='sale_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='sale_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
