# Generated by Django 5.2.17 on 2026-08-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_pricehistory_sale_end_pricehistory_sale_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank to auto-generate from the name.', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank to auto-generate from the name.', max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank to auto-generate from the name.', max_length=280, unique=True),
        ),
    ]
